Hybrid test_exchange info
sann05/python-currencycom pull request #14
Opened 2022-08-27 14:21 UTC by andrgit

2022-08-29 07:20 UTC, sann05 requested changes
Fix the length of the line and squach all commits into one

2022-08-29 07:20 UTC, sann05 commented on integration_tests/rest/test_exchange_info.py
> +        assert len(exchange_info['symbols']) > 0, "We didn't get exchange information - Symbols "
Length of the line more than 79 symbols

2022-08-29 08:09 UTC, andrgit commented on integration_tests/rest/test_exchange_info.py
> +        assert len(exchange_info['symbols']) > 0, "We didn't get exchange information - Symbols "
ok

2022-08-30 08:10 UTC, sann05 requested changes

2022-08-30 08:10 UTC, sann05 commented on integration_tests/rest/test_exchange_info.py
> +        assert (isinstance(i['symbol'], str) for i in exchange_info['symbols'])
Could you please delete it. It's not necessary

2022-08-31 09:25 UTC, andrgit commented
Удалил последнюю проверку, сделал комит

2022-09-01 09:54 UTC, sann05 requested changes
Отлично! Теперь все эти коммиты нужно собрать в 1.
Эта операция называется `squash`
Можешь сам попробовать, могу тебе помочь

2022-09-02 06:56 UTC, merged