Hybrid
sann05/python-currencycom pull request #9
Opened 2022-08-25 07:33 UTC by Trivium0911

Added test_aggTrades.py

2022-08-25 07:36 UTC, sann05 commented
Так первое - название пулл реквеста должно соответствовать названию задачи в trello, но поскольку ее не было, просто нужно написать что ты сделал. Наверняка у меня будет больше одного пулл реквеста и нужно понимать что каждый из них добавляет

2022-08-25 08:06 UTC, sann05 commented on integration_tests/rest/test_aggTrades.py
> +    def test_base(self, client):
Название теста должно отражать смысл этого теста

2022-08-25 08:06 UTC, sann05 commented on integration_tests/rest/test_aggTrades.py
> +    def test_show_agg_trades(self, client):
Все эти тесты можно было засунуть в один тест, так как ты тестируешь соответствие ответа тому, что дает сваггер

2022-08-25 08:06 UTC, sann05 commented on integration_tests/rest/test_aggTrades.py
> +class TestAggTrades:
У метода get_agg_trades, кроме параметра symbol есть еще 3 параметра.
start_time
end_time
limit.

Тебе нужно протестировать позитивные сценарии:

 - Правильный ли ответ отдаеться когда даем правильный символ
 - Действительно ли параметр start_time влияет на результат запроса
 - Влияет ли параметр end_time ?
 - Влияет ли параметр limit ?
 - А если мы start_time и end_time вместе поставим?

Негативные тесты:

 - Что если неправильный символ отправим?
 - Что если start_time будет больше чем end_time?
 - Что если start_time в будущем?
 - end_time из далекого прошлого?
 - Limit некорректный (сам попробуй придумать какие могут быть некорректные значения limit)

2022-08-27 10:35 UTC, sann05 requested changes

2022-08-27 10:35 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    def get_agg_trades_with_symbol(self, client, symbol=None, start_time=None, end_time=None, limit=500):
Этот метод тебе почти никак кол-во кода не уменьшает. Он не нужен

2022-08-27 10:35 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +        assert all((trade[key] is not None for key in trade.keys())
Ты проверяешь, что приходят значения внутри dict, но нет проверки, что приходят нужные ключи, заявленные в swagger

2022-08-27 10:35 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    def test_symbol_and_types(self, client):
Подробнее пиши названия для тестов. В этом случае
test_response_corresponds_swagger_schema или что-то в этом духе

2022-08-27 10:35 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +        date_5_min_ago = (datetime.now() - timedelta(minutes=5))
1. Date - это все что касаеться даты. У тебя это datetime или timestamp. Можно сокращать dttm или ts
2. скобки не обязательны

2022-08-27 10:35 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +        assert all(dct["T"] / 1000 > date_5_min_ago_timestamp for dct in agg_trades)
Тут точно строгое больше? не >= ?

2022-08-27 10:35 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +        date_5_min_ago = (datetime.now() - timedelta(minutes=5))
Для end_time наоборот лучше дату попозже поставить. Посмотри на сколько поздно можно (если месяц подходит - то лучше месяц)

2022-08-27 10:35 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +        assert len(agg_trades_1) != len(agg_trades_2)
Нужно проверять, что длина равна лимиту

2022-08-27 10:35 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    def test_wrong_symbol(self, client):
Вот посмотри как правильно делать тесты, которые вызывают ошибки
https://stackoverflow.com/a/29855337/6097123

2022-08-27 10:35 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    def test_incorrect_limit(self, client):
Погугли декоратор
`@pytest.mark.parametrize`

2022-08-27 13:18 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +    def test_incorrect_limit(self, client):
done

2022-08-29 08:05 UTC, sann05 requested changes

2022-08-29 08:05 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    type_err_values = ["PEACE", ['1', 2], {"a": 1}, tuple([1, 3]), map(list, "PEACE")]
Длина строки не должна превышать 79 символов
PS. Оставил только один коммент, но нужно пофиксать все строки

2022-08-29 08:05 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +        assert all(dct["T"] / 1000 >= dttm_5_min_ago_ts for dct in agg_trades)
Оставлял тут коммент по поводу точно ли строго больше.
 - Нужно было проверить есть ли случаи когда ты указываешь время и приходит trade, из-за которого тест со строгим знаком падает
 - Если все же >= это правильный знак, то его нужно было применить во всех тестах, где ты проверяешь фильтр по start_time
 - Для end_time нужно было сделать отдельную проверку, чтобы понять какой знак нужно использовать (в условиях проекта, нужно было бы просто спросить разработчиков, какой знак должен быть)

2022-08-29 08:05 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +        with pytest.raises(OSError):
Откуда OSError? У меня просто не приходят agg_trades

2022-08-29 08:05 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    def test_limit_is_more_then_maximum(self, client):
Такие тесты нужно параметризировать:
То есть проверять не только для одного значения, а проверить несколько. Например:
1001, 5000, sys.maxsize - 1, sys.maxsize

2022-08-29 08:05 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('limit', values)
Тут нет смысла отдельно сохранять значения в переменную, как и в тесте ниже

2022-08-29 08:05 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    def test_limit_for_type_err(self, client, limit):
Такой тест это перебор. Тут мы уже начинаем тестировать Python, а не api

2022-08-29 08:05 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    def test_start_time(self, client):
Тесты где ты проверяешь какое-то значение нужно параметризировать, а то в негативных ты проверил несколько значений, а в позитивных только одно.
PS. Касается всех тестов

2022-08-30 08:33 UTC, sann05 requested changes
Уже ближе, но много лишнего

2022-08-30 08:33 UTC, sann05 commented on currencycom/client.py
> +            raise ValueError('Limit {} not among acceptable wrong_values: {}'.format(
Все ж правильно было, зачем ты поменял?

2022-08-30 08:33 UTC, sann05 commented on currencycom/client.py
> +            "wrong_values": [
Видимо случайно захватил

2022-08-30 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    wrong_values = [-20, 15.3, 0]
Юра не нужно выносить эти параметры в отдельные переменные для теста, если ты их не переиспользуешь

2022-08-30 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    symbols = ['EUR/USD_LEVERAGE', 'ETH/USD_LEVERAGE', 'BCH/BTC_LEVERAGE']
Если уж хочешь параметризировать, то выбирай максимально разные символы. Например: валюты, крипта, акции и т.п.

2022-08-30 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('minutes', values)
Чаще всего ошибки в софте совершаются возле граничных значений. Поэтому то, что ты проверяешь - это цифры из одной и той же области. 
Лучше тестировать следующие значения: 0, 1, 60, (кол-во минут, чтобы время стало 1970-01-01 00:01) и (кол-во минут, чтобы время стало 1970-01-01 00:00)
Почитай как тестируются цифры.

2022-08-30 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('days', values)
То же самое что и со start_time, только для end_time валидные значения будут другие

2022-08-30 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('minutes', values)
Тут точно не нужна параметризация, а если и ставить ее, то нужно для разницы между start_time и end_time. 
Причем, чтобы end_time не была datetime.now()

2022-08-30 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('limit', values)
Та же самая история, что и с start_time

2022-08-30 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('minutes', values)
Та же история, что и start_time

2022-08-30 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    values_over_limit = [1001, 6666, 110993, 4815162342]
1001 понятно, а что за остальные цифры?

2022-08-30 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('symbol', wrong_symbols)
Одного символа будет достаточно

2022-08-30 08:46 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +        with pytest.raises(Exception):
Лучше конкретизировать, но тут вообще ошибки быть не должно

2022-08-30 08:53 UTC, Trivium0911 commented on currencycom/client.py
> +            raise ValueError('Limit {} not among acceptable wrong_values: {}'.format(
Эммм, лично я тут ничего не менял)

2022-08-30 08:57 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +    wrong_values = [-20, 15.3, 0]
Done

2022-08-30 08:59 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +    symbols = ['EUR/USD_LEVERAGE', 'ETH/USD_LEVERAGE', 'BCH/BTC_LEVERAGE']
Там какой-то косяк, когда без LEVERAGE отправляешь одну валюту. Я потому 3 и оставил

2022-08-30 14:38 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('limit', values)
done

2022-08-30 14:38 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('minutes', values)
done

2022-08-30 14:43 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +        with pytest.raises(OSError):
Fixed this problem

2022-08-30 14:44 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +        with pytest.raises(Exception):
fixed

2022-08-30 14:45 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('symbol', wrong_symbols)
done

2022-08-31 07:51 UTC, Trivium0911 commented on currencycom/client.py
> +            "wrong_values": [
Всё понял, всё исправил

2022-08-31 07:56 UTC, Trivium0911 commented on currencycom/client.py
> +            raise ValueError('Limit {} not among acceptable wrong_values: {}'.format(
Понял косяк, исправил

2022-08-31 07:57 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +    symbols = ['EUR/USD_LEVERAGE', 'ETH/USD_LEVERAGE', 'BCH/BTC_LEVERAGE']
Понял плюшки параметризации и как писать массивы данных. Исправил

2022-08-31 08:33 UTC, sann05 requested changes
Юра, я тебя очень прошу внимательно пройтись по каждому комментарию

2022-08-31 08:33 UTC, sann05 commented on currencycom/client.py
> +            raise ValueError('Limit {} not among acceptable wrong_values: {}'.format(
Скорее всего, ты когда пытался переименовать все разом зацепил штуки из основной библиотеки. Откати плс обратно

2022-08-31 08:33 UTC, sann05 commented on currencycom/client.py
> +            "wrong_values": [
Гит не ошибся! А вот ты мог случайно поменять незаметив

2022-08-31 08:33 UTC, sann05 commented on currencycom/client.py
> -
Убрал строку, там где не нужно было.
Внимательней смотри на File changed вкладку после пуша

2022-08-31 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +        datetime(1970, 1, 3) + timedelta(minutes=1),
А можно сразу сделать это в datetime(1970, 1, 3, 0, 1) ?
Меньше операций, если не мешает читабельности - лучше

2022-08-31 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('symbol', ['EUR/USD_LEVERAGE',
Либо оставь один символ, либо проверяй рынки из разных секторов.

2022-08-31 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +                                         'ETH/USD_LEVERAGE',
Убедишь, что все выравнено красиво перед отправлением. Это style guide

2022-08-31 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    def test_end_time(self, client):
Почему для end_time только один?

2022-08-31 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('dttm', date_values)
Этот тест неверно сконструирован. 
Валидный промежуток, который тебе нужно проверять - это 1 час (разница между start_time и end_time)
Соответственно 5 валидных значений должны быть на основе этого промежутка.
При этом важно, чтобы ни одно из значений не было datetime.now()

2022-08-31 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('dttm', date_values)
Точно так же как и в случае с валидным тестом - валидный рэнж это 1 час.
Нужно проверить, варианты за пределами этого часа

2022-08-31 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    def test_start_time_in_future(self, client):
Мы же говорили, что как минимум 2 значения с одной стороны.
now() + 1 и + бесконечность (в твоем случае это три тысячи какой-то год)

2022-08-31 08:33 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +        wrong_values = [-20, -1, 0, 15.3]
Это же классика для параметризированного теста.
-20 это что-то из минус бесконечности?

2022-08-31 10:14 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +        datetime(1970, 1, 3) + timedelta(minutes=1),
Исправил

2022-08-31 10:15 UTC, Trivium0911 commented on currencycom/client.py
> -
Сделано

2022-08-31 10:16 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('symbol', ['EUR/USD_LEVERAGE',
Оставил 1 символ

2022-08-31 10:30 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +    def test_end_time(self, client):
Добавил параметризацию для date_values

2022-08-31 10:44 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +    def test_start_time_in_future(self, client):
Добавил  datetime(3001, 1, 3)

2022-08-31 10:45 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +        wrong_values = [-20, -1, 0, 15.3]
Изменил на -99999

2022-08-31 14:27 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('dttm', date_values)
Не совсем понятно. Здесь проверяются кейсы, когда end_time меньше чем start_time. Не совсем понимаю, при чём тут разница в час? Тут даже если end_time меньше на минуту, тест пришлёт "startTime should be less than endTime"

2022-08-31 14:29 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +        wrong_values = [-20, -1, 0, 15.3]
поменял на -sys.maxsize

2022-08-31 15:00 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +    @pytest.mark.parametrize('dttm', date_values)
Done

2022-08-31 15:05 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +                                         'ETH/USD_LEVERAGE',
Аддон PEP 8 не ругается. Поправил

2022-09-01 09:51 UTC, sann05 requested changes
Юра, ты уже у финишной черты!!!

2022-09-01 09:51 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +        datetime(1995, 1, 1),
Врядли эта биржа работала в 1995, давай хотябы 2019 поставим

2022-09-01 09:51 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +        dttm_ago_ts = datetime.timestamp(dttm)
dttm - это уже datetime. Лучше написать
```
dttm.timestamp()
```

2022-09-01 09:51 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +        agg_trades = client.get_agg_trades(symbol="PEACE")
Что за `PEACE` ? :)

Может лучше что-то что вроде `TEST123` - такой symbol врядли кто-то будет занимать

2022-09-01 09:51 UTC, sann05 commented on integration_tests/rest/test_agg_trades.py
> +    def test_end_time_long_time_ago(self, client):
Давай этот тест тоже запарметризируем

2022-09-01 09:54 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +        datetime(1995, 1, 1),
Done

2022-09-01 09:58 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +        dttm_ago_ts = datetime.timestamp(dttm)
Done

2022-09-01 10:00 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +        agg_trades = client.get_agg_trades(symbol="PEACE")
Fixed

2022-09-01 10:09 UTC, Trivium0911 commented on integration_tests/rest/test_agg_trades.py
> +    def test_end_time_long_time_ago(self, client):
datetime(1970, 1, 3),
datetime(1970, 1, 3, 0, 0, 1)

2022-09-01 10:33 UTC, sann05 requested changes
Отлично! Теперь осталось только собрать все коммиты в 1
Операция называеться squash.
Хочешь могу помочь

2022-09-01 13:14 UTC, closed without merging